CREATE TABLE CADASTRO(
	CPF char(11),
	DataNascimento DATE NOT NULL,
	Email varchar(100) NOT NULL UNIQUE,
	Senha varchar(50) NOT NULL,
	Nome varchar(100) NOT NULL,
	Pais varchar(50) NOT NULL,
	Estado varchar(50) NOT NULL,
	Cidade varchar(50) NOT NULL,
	Bairro varchar(50) NOT NULL,
	Rua varchar(50) NOT NULL,
	Numero int,
	Complemento varchar(100),

	PRIMARY KEY(CPF)	
);

CREATE TABLE TIPO_QUARTO(
	Tipo VARCHAR(50),
	Descricao VARCHAR(100) NOT NULL,
	ValorDiaria REAL NOT NULL,

	PRIMARY KEY(Tipo)
);

CREATE TABLE QUARTO(
	Numero int,
	Tipo VARCHAR(50),
	Status BOOLEAN NOT NULL,

	PRIMARY KEY(Numero),
	FOREIGN KEY(Tipo) REFERENCES TIPO_QUARTO(Tipo) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE RESERVA(
	Codigo int,
	Data DATE NOT NULL,
	Status BOOLEAN NOT NULL,
	Tipo VARCHAR(50) NOT NULL ,
	NumQuarto INT,

	PRIMARY KEY(Codigo),
	FOREIGN KEY(NumQuarto) REFERENCES QUARTO(numero) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE HOSPEDE(
	ID SERIAL,
	CpfCadastrado CHAR(11),
	MotivoViagem VARCHAR(100),
	LocalOrigem VARCHAR(100),
	LocalDestino VARCHAR(100),
	NumQuarto INT,

	PRIMARY KEY(ID),
	FOREIGN KEY(CpfCadastrado) REFERENCES CADASTRO(CPF) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY(NumQuarto) REFERENCES QUARTO(Numero) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE CHECAGEM(
	Codigo INT,
	DataMarcada DATE NOT NULL,
	HoraMarcada TIME NOT NULL,
	Data DATE NOT NULL,
	Hora TIME NOT NULL,
	Status BOOLEAN NOT NULL,
	Observacao VARCHAR(100),
	IdHospede INT,
	Tipo VARCHAR(10) NOT NULL,

	PRIMARY KEY(Codigo),
	FOREIGN KEY(IdHospede) REFERENCES HOSPEDE(ID) ON UPDATE CASCADE ON DELETE RESTRICT	
);

CREATE TABLE CONTA(
	NotaFiscal VARCHAR(30),
	ValorTotal  REAL NOT NULL,
	Data DATE NOT NULL,
	Status BOOLEAN NOT NULL,
	CodReserva INT,

	PRIMARY KEY(NotaFiscal),
	FOREIGN KEY(CodReserva) REFERENCES RESERVA(Codigo) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE SERVICO_ACADEMIA(
	IdServExtra INT,
	Valor REAL NOT NULL,
	DuracaoTreino INT  NOT NULL,
	TipoTreino VARCHAR(50) NOT NULL,
	CodReserva INT,
	DataSolicitada DATE NOT NULL,
	HoraSolicitada TIME NOT NULL,

	PRIMARY KEY(IdServExtra),
	FOREIGN KEY(CodReserva) REFERENCES RESERVA(codigo) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE SERVICO_LAVANDERIA(
	IdServExtra INT,
	Valor REAL NOT NULL,
	CodReserva INT,
	DataSolicitada DATE NOT NULL,
	HoraSolicitada TIME NOT NULL,

	PRIMARY KEY(IdServExtra),
	FOREIGN KEY(CodReserva) REFERENCES RESERVA(codigo) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE SERVICO_BAR_RESTAURANTE(
	IdServExtra INT,
	Valor REAL NOT NULL,
	CodReserva INT,
	DataSolicitada DATE NOT NULL,
	HoraSolicitada TIME NOT NULL,

	PRIMARY KEY(IdServExtra),
	FOREIGN KEY(CodReserva) REFERENCES RESERVA(codigo) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE SERVICO_FRIGOBAR(
	IdServExtra INT,
	Valor REAL NOT NULL,
	CodReserva INT,
	DataSolicitada DATE NOT NULL,
	HoraSolicitada TIME NOT NULL,

	PRIMARY KEY(IdServExtra),
	FOREIGN KEY(CodReserva) REFERENCES RESERVA(codigo) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE PRODUTO(
	Codigo INT, 
	Nome VARCHAR(50) NOT NULL,
	Preco REAL NOT NULL,

	PRIMARY KEY(Codigo)
);

CREATE TABLE PECA(
	Tipo VARCHAR(30),
	Preco REAL NOT NULL,

	PRIMARY KEY(TIPO)
); 

CREATE TABLE TEM_RESERVA(
	IdHospede SERIAL, 
	CodReserva INT,

	PRIMARY KEY(IdHospede, CodReserva),
	FOREIGN KEY(CodReserva) REFERENCES RESERVA(Codigo) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY(IdHospede) REFERENCES HOSPEDE(Id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE ACOMPANHANTES(
	IdAcompanhante SERIAL,
	idHospedePrincipal SERIAL,

	PRIMARY KEY(IdAcompanhante, idHospedePrincipal),
	FOREIGN KEY(IdAcompanhante) REFERENCES HOSPEDE(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY(idHospedePrincipal) REFERENCES HOSPEDE(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE LAVANDERIA_LAVA_PECA(
	IdServExtraLavanderia INT,
	TipoPeca VARCHAR(30),
	Quantidade INT NOT NULL,
	ValorLavagem REAL NOT NULL,

	PRIMARY KEY(IdServExtraLavanderia, TipoPeca),
	FOREIGN KEY(IdServExtraLavanderia) REFERENCES SERVICO_LAVANDERIA(IdServExtra) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY(TipoPeca) REFERENCES PECA(TIPO) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE BAR_TEM_PRODUTO(
	IdServExtraBar INT,
	CodProduto INT,
	Quantidade INT NOT NULL,
	ValorVenda REAL NOT NULL,

	PRIMARY KEY(IdServExtraBar, CodProduto),
	FOREIGN KEY(IdServExtraBar) REFERENCES SERVICO_BAR_RESTAURANTE(idServExtra) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY(CodProduto) REFERENCES PRODUTO(Codigo) ON UPDATE CASCADE ON DELETE RESTRICT

);

CREATE TABLE FRIGOBAR_TEM_PRODUTO(
	IdServExtraBar INT,
	CodProduto INT,
	Quantidade INT NOT NULL,
	ValorVenda REAL NOT NULL,

	PRIMARY KEY(IdServExtraBar, CodProduto),
	FOREIGN KEY(IdServExtraBar) REFERENCES SERVICO_FRIGOBAR(idServExtra) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY(CodProduto) REFERENCES PRODUTO(Codigo) ON UPDATE CASCADE ON DELETE RESTRICT	
);

CREATE TABLE TELEFONE_CADASTRO(
	CpfCadastrado CHARACTER(11),
	Telefone VARCHAR(15),
	
	PRIMARY KEY(CpfCadastrado, Telefone),
	FOREIGN KEY(CpfCadastrado) REFERENCES CADASTRO(CPF)	ON UPDATE CASCADE ON DELETE CASCADE
);